pipeline {
  agent any
  stages {
    stage('Back-end') {
      agent {
        docker { image 'maven:3.8.1-adoptopenjdk-11' }
      }
      steps {
        sh 'mvn --version'
      }
    }
    stage('Front-end') {
      agent {
        docker { image 'node:16-alpine' }
      }
      steps {
        sh 'node --version'
      }
    }
    stage('Checkout Code') {
      steps {
        git branch: 'main'
        url: 'https://github.com/HarshaVardhan49/Jenkins-prac-repo/tree/main/multi-stage-multi-agent'
      }
    }
    stage('Compile') {
      steps {
        sh 'javac Helloworld.java'
      }
    }
    stage('Run') {
      steps {
        sh 'java Jenkins Helloworld'
      }
    }
  }
}
